spring:
  application:
    name: interaction-api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
feign:
  client:
    config:
      warehouse:
        loggerLevel: full