spring:
  application:
    name: analyzer
  config:
    import: configserver:http://localhost:9191
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

  eureka:
    instance:
      hostname: localhost
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/